### ISSUE TITLE
Flex Issue in src/sections/Example.tsx

### ISSUE THREAD

**Issue by FFMerlin-aracom** [Pipo93/storybook-storycreator#10]
Hi Philip!

We found a small bug, where some components (especially images) weren't displayed correctly (Safari works fine, but Chrome has some problems here). We already found the fix for that, if you remove the "flex: 1" in Line 74 everything works fine.

Could you please add this fix?

Greetings,
Felix

**Comment by Pipo93** [comment]
I‘ll try to publish a new version tomorrow morning :)

**Comment by Pipo93** [comment]
@FFMerlin-aracom should be fixed in `1.0.0-beta.7` and ` 0.0.1-beta.11`, dependent of which version you are using. You can try both :D
